name: Pipeline

on:
  push:
    branches:
      - main
      - pipeline-testing
  pull_request:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.12.1
          
      - name: npm install
        run: |
          npm install

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
