name: Pipeline

on:
  push:
    branches:
      - main
      - pipeline-testing
  pull_request:
    branches: [main]
    
jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.12.1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
